name: kaiserbear
favicon: null
layout_spectrum: 0.8607832740526646
typography_spectrum: 0.9620222407393157
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.47316657775081694
  lightness: 0.3356830012053251
  saturation: 0.40633351844735444
  rhythmicContrast: 0.15543682081624866
purpose: []
